[package]
name = "medial_axis_3d"
version = "0.1.0"
authors = ["Andrei Toterman <andrei.toterman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.26.2"
raylib = "3.5.0"
